### ISSUE TITLE
Relax prism version constraint

### ISSUE THREAD

**Issue by gmcgibbon** [Shopify/rbi#266]
Right now, we have an upper-bound version constraint on Prism here: https://github.com/Shopify/rbi/blob/15448ad2b5b0ca3b034482b8be6d007a70c25cbb/rbi.gemspec#L27

It looks like the original reason for this was to prevent a breaking change from affecting RBI in https://github.com/Shopify/rbi/commit/2abfa69695a92ba92ae15caa32c21590ea95fb23. In practice, this works well in the moment, but when applications need to specify a new version of Prism, they can't (because RBI is being strict for seemingly no reason).

This seems to have caused more strain on maintainers of RBI to release [a new version for every version bump of a dependency](https://github.com/Shopify/rbi/releases), and that doesn't make sense. Can we relax this dependency to either:

- Remove the upper-bound entirely, and expect maintainers of Prism to fix unintended breaking changes with subsequent releases.
- Restrict to the next major version (1.0), and trust Prism to introduce breaking changes intentionally with a major version bump.

I'm asking because I got bit by this while testing a patch on Packwerk [that's attempting to use Prism](https://github.com/Shopify/packwerk/pull/388).

**Comment by vinistock** [comment]
Prism might still go through breaking changes in the Ruby API while the team works to integrate it with the Ruby compiler. We can't relax the constraints until the API is stabilized or we risk breaking `rbi` on a minor release from Prism.

We're waiting for confirmation from the team working on Prism that the API is stable and then we can relax the constraints and use major versions as the indicator of breaking changes.

**Comment by andyw8** [comment]
But might this also be an indication that we don't have full confidence in `rbi`'s tests? Would improving those help to mitigate the risk of breaking changes?
