### ISSUE TITLE
Final modifier is omitted when signature is rendered as block

### ISSUE THREAD

**Issue by dnvkv** [Shopify/rbi#316]
When RBI files are rendered, `final` modifier is omitted if the signature is rendered as multiline block. When it is rendered as single line, `final` modifier is preserved. I assume it happens [here](https://github.com/Shopify/rbi/blob/main/lib/rbi/printer.rb#L643) in the method `RBI::Printer#print_sig_as_line` with `print("(:final)") if node.is_final`. There's no such check in method `RBI::Printer#print_sig_as_block`.

I can prepare a PR to fix it by updating this [line](https://github.com/Shopify/rbi/blob/main/lib/rbi/printer.rb#L669) from
```ruby
printl("sig do")
```
to
```ruby
if node.is_final
  printl("sig(:final) do")
else
  printl("sig do")
end
```

**Comment by Morriar** [comment]
👋 Hey @dnvkv, I pushed a fix with https://github.com/Shopify/rbi/pull/318. Can you give it a try please? Thanks!

**Comment by dnvkv** [comment]
@Morriar Thank you! It fixed my problem!
