### ISSUE TITLE
v0.0.7 incompatible with tapioca?

### ISSUE THREAD

**Issue by bmulholland** [Shopify/rbi#97]
After upgrading to the recently-released v0.0.7, `srb tc` fails with the following:

```
sorbet/rbi/gems/tapioca@0.5.4.rbi:159: Method RBI::Tree#merge redefined without matching argument count. Expected: 4, got: 1 https://srb.help/4010
     159 |  def merge(other); end
            ^^^^^^^^^^^^^^^^
    sorbet/rbi/gems/rbi@0.0.7.rbi:1308: Previous definition
    1308 |  def merge(other, left_name: T.unsafe(nil), right_name: T.unsafe(nil), keep: T.unsafe(nil)); end
```

As there is no changelog and no migration steps posted for this gem, I assume there aren't any steps I'm supposed to take to resolve this issue myself.

**Comment by Morriar** [comment]
👋 Hey Brendan,

We [bumped the version requirement in Tapioca](https://github.com/Shopify/tapioca/pull/613/files#diff-b785684e022a6a7c356d492c49a02fce85b3325277cfe59f9cb511c50449e838R28). This should be fixed as soon as we release Tapioca v0.5.5.

In the mean time you can constrain the version of RBI in your project.

Thanks for the report 🙏
